CREATE WAREHOUSE six_large 
WITH 
WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
WAREHOUSE_SIZE = X6LARGE
MAX_CLUSTER_COUNT = 2
MIN_CLUSTER_COUNT = 1
SCALING_POLICY = ECONOMY
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = '6X-Large warehouse'
ENABLE_QUERY_ACCELERATION = TRUE;

SHOW WAREHOUSES;

ALTER WAREHOUSE six_large SUSPEND;

SHOW WAREHOUSES LIKE '%ARU%';