CREATE WAREHOUSE power_house 
WITH 
WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
WAREHOUSE_SIZE = LARGE
MAX_CLUSTER_COUNT = 2
MIN_CLUSTER_COUNT = 1
SCALING_POLICY = STANDARD
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
COMMENT = 'To improve performance'
ENABLE_QUERY_ACCELERATION = TRUE;

CREATE OR REPLACE ROLE data_scientist;

GRANT USAGE ON WAREHOUSE power_house TO data_scientist;

SHOW ROLES;

CREATE USER ds_1 PASSWORD='ds_1' LOGIN_NAME = 'ds_1'
DEFAULT_ROLE = 'data_scientist'
DEFAULT_WAREHOUSE = 'power_house'
MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE data_scientist TO USER ds_1;

SHOW USERS;

ALTER USER THARUN
SET default_warehouse = 'THARUN';