SELECT * FROM ORDERS

SELECT * FROM REGION 

SELECT * FROM NATION

SELECT R.R_NAME, SUM(O.O_TOTALPRICE) FROM REGION R
JOIN NATION N ON R.R_REGIONKEY = N.N_REGIONKEY
JOIN CUSTOMER C ON N.N_NATIONKEY = C.C_NATIONKEY
JOIN ORDERS O ON O.O_CUSTKEY = C.C_CUSTKEY
GROUP BY R.R_NAME

CREATE OR REPLACE DATABASE my_practice_db
CREATE OR REPLACE SCHEMA day_1

USE my_practice_db

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER

CREATE OR REPLACE TABLE my_top_customers AS 
SELECT C.C_NAME, SUM(O.O_TOTALPRICE) AS TOTAL_AMOUNT FROM 
SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C 
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O 
ON C.C_CUSTKEY = O.O_CUSTKEY
GROUP BY C.C_CUSTKEY, C.C_NAME
ORDER BY SUM(O.O_TOTALPRICE) DESC 
LIMIT 20

SELECT * FROM my_top_customers