CREATE OR REPLACE TABLE first_100_customers 
AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
ORDER BY C_CUSTKEY ASC
LIMIT 100;

SELECT * FROM first_100_customers;

CREATE OR REPLACE TABLE first_100_customers_orders AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
WHERE O_CUSTKEY IN (SELECT C_CUSTKEY FROM first_100_customers);

SELECT COUNT(*) AS total_orders FROM first_100_customers_orders;

SHOW TABLES;